Splash screen
Coding4Buddies/BatShooter pull request #1
Opened 2022-01-21 10:51 UTC by nickichann01

Created Splash Screen for the Game

2022-01-21 10:52 UTC, nickichann01 commented
Missing the Main Screen when the Splash Screen is Finished.

2022-01-21 13:00 UTC, Jookie262 requested changes
Apply changes in the Label area

2022-01-21 13:00 UTC, Jookie262 commented on src/main/java/com/coding4buddies/batshooter/SplashScreen.java
> +        this.add(label);
Make the color of label to black and adjust the font size. Also add a space between the progress bar.

2022-01-21 13:50 UTC, Jookie262 commented on src/main/java/com/coding4buddies/batshooter/SplashScreen.java
> +        this.add(label);
Also if possible, change the image of splash screen

2022-01-22 16:10 UTC, Jookie262 approved these changes
Everything is good!

2022-01-22 16:11 UTC, merged